version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 095314342340.dkr.ecr.ap-south-1.amazon
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Image tag is $IMAGE_TAG"
  build:
    commands:
      - echo building application
      - mvn clean install
      - echo Building Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $ECR_REPO_URI:$IMAGE_TAG
      - docker tag $REPO_NAME:latest $ECR_REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo Writing image definitions...
      - printf '[{"name":"BHFL-Escrow-Portal-Backend-UAT-Container","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Generating AppSpec.json..."
      - |
        printf '{
          "version": 1,
          "Resources": [
            {
              "TargetService": {
                "Type": "AWS::ECS::Service",
                "Properties": {
                  "TaskDefinition": "%s",
                  "LoadBalancerInfo": {
                    "ContainerName": "%s",
                    "ContainerPort": %d
                  }
                }
              }
            }
          ]
        }' "$TASK_DEFINITION_ARN" "$CONTAINER_NAME" $CONTAINER_PORT > AppSpec.json
artifacts:
  files:
    - imagedefinitions.json
    - AppSpec.json
