version: 0.2
phases:
  install:
    commands:
      - echo "installing NGINX"
      - apt-get update
      - apt-get install nginx -y

  build:
    commands:
      - echo Build sterted on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
