version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Image tag is $IMAGE_TAG"
  
  install:
    commands:
      - echo "installing NGINX"
      # Enable the Nginx package from Amazon Linux Extras
      - sudo amazon-linux-extras enable nginx1

# Install Nginx
      - sudo yum install nginx -y

# Start the Nginx service
      - sudo systemctl start nginx

# Enable Nginx to start on boot
      - sudo systemctl enable nginx

# Check Nginx status
      - sudo systemctl status nginx

  build:
    commands:
      - echo Build sterted on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
